stages:
  - build
  - release

before_script:
  - export JAVA_HOME=/home/sdks/zulu-17
  - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

build:
  stage: build
  script:
    - ./gradlew build publish --info --no-daemon
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 1 days
  only:
    - master
  tags:
    - linux

create-release:
  stage: release
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  before_script:
    - echo "Fetching project version from libs.versions.toml"
    - export PROJECT_VERSION=$(./gradlew generateVersionInfo --quiet)
  script:
    - echo "Creating release for version $PROJECT_VERSION.$CI_PIPELINE_IID"
  release:
    tag_name: '$(cat .version).$CI_PIPELINE_IID'
    description: '$(cat .version).$CI_PIPELINE_IID'
    ref: '$CI_COMMIT_SHA'
  tags:
    - linux
