modLoader = "javafml" #mandatory
loaderVersion = "${loader_version_range}" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license = "${mod_license}"
issueTrackerURL = "https://git.karmakrafts.dev/kk/mc-projects/chemlib-custom-compounds/-/issues"
displayURL = "https://git.karmakrafts.dev/kk/mc-projects/chemlib-custom-compounds"

[[mods]] #mandatory
modId = "${mod_id}" #mandatory
logoFile = "chemlibcc_logo.png"
version = "${mod_version}" #mandatory
displayName = "${mod_name}" #mandatory
authors = "${mod_authors}" #optional
description = '''${mod_description}'''
updateJSONURL = "https://git.karmakrafts.dev/kk/mc-projects/chemlib-custom-compounds/-/raw/master/versions.json?ref_type=heads"
credits = """
"""

[[dependencies.${ mod_id }]] #optional
modId = "forge" #mandatory
mandatory = true #mandatory
versionRange = "${forge_version_range}" #mandatory
ordering = "NONE"
side = "BOTH"

[[dependencies.${ mod_id }]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${ mod_id }]]
modId = "chemlib"
mandatory = true
versionRange = "[2.0.19,)"
ordering = "AFTER"
side = "BOTH"

[modproperties.${ mod_id }]
catalogueImageIcon = "chemlibcc_logo.png"
